#!/bin/sh -e

case "$1" in
    configure)
    adduser --system --group --no-create-home --quiet plight || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    echo "preinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
